### ISSUE TITLE
Error code - SL Preptach

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Ravendwyr/HandyNotes_HallowsEnd#9] opened 2020-10-25 11:30 UTC
Hello, I keep getting this error code:

> 1x HandyNotes_HallowsEnd\Core.lua:228: attempt to call upvalue 'GetQuestsCompleted' (a nil value)
> [string "@HandyNotes_HallowsEnd\Core.lua"]:228: in function <HandyNotes_HallowsEnd\Core.lua:201>
> [string "@HandyNotes_HallowsEnd\Core.lua"]:300: in function <HandyNotes_HallowsEnd\Core.lua:256>
> [string "=[C]"]: ?
> [string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
> [string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
> [string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
> [string "=[C]"]: ?
> [string "=[C]"]: in function `LoadAddOn'
> [string "@BattlePetCageMatch\BattlePetCageMatch-V3.0.lua"]:1141: in function <...aceBattlePetCageMatch\BattlePetCageMatch.lua:1130>
> [string "=[C]"]: ?
> [string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
> [string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
> ...
> [string "=[C]"]: ?
> [string "@ElvUI_SLE\core\toolkit.lua"]:307: in function `InitializeModules'
> [string "@ElvUI_SLE\core\core.lua"]:85: in function `?'
> [string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:303: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:299>
> [string "=[C]"]: in function `Initialize'
> [string "@ElvUI\init.lua"]:156: in function <ElvUI\init.lua:155>
> [string "=[C]"]: ?
> [string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
> [string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
> [string "@Masque\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Am I doing something wrong?

**Comment by Ravendwyr** [comment] 2020-10-25 22:11
Duplicate of #8

**Closed by Ravendwyr** 2020-10-25 22:11 UTC
